# Generated by Django 5.0.1 on 2025-07-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
