# Generated by Django 5.0.1 on 2025-08-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_body',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
