# Generated by Django 5.0.1 on 2025-08-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_item_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('product_link', models.URLField()),
                ('current_price', models.CharField(max_length=50)),
                ('carton_price', models.CharField(blank=True, max_length=50)),
                ('single_price', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('item_code', models.CharField(blank=True, max_length=50)),
                ('supplier', models.CharField(blank=True, max_length=50)),
                ('supplier_url', models.CharField(blank=True, max_length=50)),
                ('item_body', models.CharField(blank=True, max_length=500)),
                ('item_quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
