# Generated by Django 5.0.1 on 2025-09-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_body',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
